Fix IndexOutOfBounds in RecursiveNumericEvaluator
apache/solr pull request #1054
Opened 2022-10-07 10:22 UTC by acsbendi

# Description

This change fixes the following exception:
```
2022-10-04 12:21:26.033 ERROR (qtp503938393-25) [...] o.a.s.c.s.i.s.ExceptionStream java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 => java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).eval.RecursiveNumericEvaluator.normalizeInputType(RecursiveNumericEvaluator.java:55) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).eval.RecursiveEvaluator.recursivelyEvaluate(RecursiveEvaluator.java:214) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).eval.RecursiveEvaluator.evaluate(RecursiveEvaluator.java:202) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).stream.LetStream.open(LetStream.java:195) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).stream.ExceptionStream.open(ExceptionStream.java:49) ~[?:?]
        at org.apache.solr.handler.StreamHandler$TimerStream.open(StreamHandler.java:486) ~[?:?]
        at [org.apache.solr.client.solrj.io](http://org.apache.solr.client.solrj.io/).stream.TupleStream.writeMap(TupleStream.java:77) ~[?:?]
        at org.apache.solr.common.util.JsonTextWriter.writeMap(JsonTextWriter.java:168) ~[?:?]
        at org.apache.solr.common.util.TextWriter.writeMap(TextWriter.java:241) ~[?:?]
        at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:85) ~[?:?]
        at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:205) ~[?:?]
        at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:45) ~[?:?]
        at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:387) ~[?:?]
        at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:295) ~[?:?]
        at org.apache.solr.response.JSONWriter.writeResponse(JSONWriter.java:77) ~[?:?]
        at org.apache.solr.response.JSONResponseWriter.write(JSONResponseWriter.java:63) ~[?:?]
        at org.apache.solr.response.QueryResponseWriterUtil.writeQueryResponse(QueryResponseWriterUtil.java:71) ~[?:?]
        at org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:999) ~[?:?]
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:631) ~[?:?]
        at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:239) ~[?:?]
        at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:207) ~[?:?]
        at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:257) ~[?:?]
        at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:227) ~[?:?]
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:202) ~[?:?]
```
# Solution

I check if the list if empty before accessing its first item.

# Tests

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2022-10-14 20:09 UTC, risdenk commented
@acsbendi can you add a test case for this? looks like its a streaming expression potentially?

2022-10-14 20:09 UTC, risdenk requested changes
@acsbendi can you add a test case for this? looks like its a streaming expression potentially?

2022-10-17 08:17 UTC, acsbendi commented
@risdenk Sure, where should I add one? Yes, this happened in a streaming expression, should I add a test for that streaming expression?

2022-10-17 15:49 UTC, risdenk commented
@acsbendi https://github.com/apache/solr/blob/main/solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java potentially or one of the other existing classes under https://github.com/apache/solr/tree/main/solr/solrj/src/test/org/apache/solr/client/solrj/io

2022-10-17 15:50 UTC, risdenk commented
I do see a https://github.com/apache/solr/blob/main/solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/eval/RecursiveEvaluatorTest.java, but no `RecursiveNumericEvaluatorTest` so take a look and see where your test case might go.

2022-10-18 08:25 UTC, acsbendi commented
@risdenk I've added a test for it, and checked that it fails without my fix:)

2022-10-18 13:55 UTC, risdenk requested changes
Thanks @acsbendi - running `./gradlew check -x test` would surface a few errors.
* `Assert....` shouldn't be needed. just use `assertEquals`
* Add license header that matches other tests

2022-10-18 13:55 UTC, risdenk commented on solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/eval/MovingAverageEvaluatorTest.java
> +package org.apache.solr.client.solrj.io.stream.eval;
Missing license header

2022-10-18 13:55 UTC, risdenk commented on solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/eval/MovingAverageEvaluatorTest.java
> +        Assert.assertEquals(Collections.emptyList(), result);
Just use `assertEquals` without `Assert.`

2022-10-18 13:58 UTC, acsbendi commented on solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/eval/MovingAverageEvaluatorTest.java
> +package org.apache.solr.client.solrj.io.stream.eval;
Fixed

2022-10-18 13:58 UTC, acsbendi commented on solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/eval/MovingAverageEvaluatorTest.java
> +        Assert.assertEquals(Collections.emptyList(), result);
Fixed

2022-10-18 13:59 UTC, acsbendi commented
My pleasure:) The problems are fixed now

2022-10-19 18:20 UTC, risdenk approved these changes
@acsbendi this looks good. I'm going to create a jira ticket and make a minor change (add solr/CHANGES.txt entry)

2022-10-20 16:44 UTC, merged

2022-10-20 16:44 UTC, risdenk commented
Thanks @acsbendi

2022-10-21 07:50 UTC, acsbendi commented
@risdenk You're welcome, glad to be able to contribute!