SOLR-16555: SolrIndexSearcher - FilterCache intersections/andNot should not clone bitsets repeatedly
apache/solr pull request #1183
Opened 2022-11-17 21:23 UTC by risdenk

https://issues.apache.org/jira/browse/SOLR-16555

2022-11-17 21:48 UTC, risdenk reviewed
I'm running through some performance tests with this over the next day or so. Will be interesting to see what shakes out.

2022-11-17 21:48 UTC, risdenk commented on solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
> +          // Clear any documents that are in the negative filter query
I need to add a comment around why not using `answer.andNot(sets[i])`

2022-11-17 21:49 UTC, dsmiley requested changes
Your first draft of this isn't going to be performant.  Instead of bulk bitSet operations, you're iterating doc-by-doc!  For small sets (SortedIntDocSet), this is fine, but for bigger ones -- no.

2022-11-17 21:51 UTC, dsmiley commented
Just to be clear, this is a highly performance critical code path.  Sadly we have no benchmarks of this that I know of but at least there's peer review.  Once the solution looks more work-able, I'll at-mention some more eye-balls.  Maybe you might consider adding to /solr/benchmark.

2022-11-17 22:03 UTC, risdenk commented
> Instead of bulk bitSet operations, you're iterating doc-by-doc! For small sets (SortedIntDocSet), this is fine, but for bigger ones -- no.

@dsmiley yea not saying this is the final version at all. I'm actually curious on testing this with some benchmarking stuff to see how much the memory allocations slowed this down. This approach requiring more CPU, but less memory. I would not disagree there is more performance using the bulk bitset operations.

2022-11-17 22:13 UTC, risdenk commented
From David on Jira an idea to explore:
> Create a subclass of BitDocSet called MutableBitDocSet. Its intersect() and andNot() methods can return itself, and be implemented that way. In getProcessedFilter, before those two tight loops that call those two methods, upgrade/replace "answer" with MutableBitDocSet if end (the number of combinations to do) is greater than 1. If it's 1 or 0 then there's no point in the upgrade.

2022-11-18 17:19 UTC, risdenk commented
This is inefficient as David pointed out and caused timeouts on a bunch of queries during testing. I was hoping to at least capture some profile from it but didn't last long enough to do that. https://github.com/apache/solr/pull/1184 is next iteration using a `MutableBitSet` as David pointed out.

2022-11-18 17:19 UTC, closed without merging