SOLR-16925 Broken JSON indentation using JacksonJsonWriter
apache/solr pull request #1941
Opened 2023-09-20 14:40 UTC by noblepaul

2023-09-20 16:24 UTC, HoustonPutman requested changes
I'm not really sure how this fixing the issue (I also tested and the issue is still there). We are already using a pretty printer, but the issue is that the pretty printer is stateful.

So basically we need to create a new instance of PrettyPrinter for every json serialization, which we can do by using the `gen.setPrettyPrinter(pretty.createInstance())` method if `pretty` is a `DefaultPrettyPrinter` object.

2023-09-20 16:24 UTC, HoustonPutman commented on solr/core/src/java/org/apache/solr/response/JacksonJsonWriter.java
>    protected static final PrettyPrinter pretty =
```suggestion
  protected static final DefaultPrettyPrinter pretty =
```

2023-09-21 08:25 UTC, noblepaul commented
`I also tested and the issue is still there`

I'm sure it did fix the issue. Your solution works just fine. I'll close this and approve that

2023-09-21 08:26 UTC, noblepaul commented
closing this in favor of #1942

2023-09-21 08:26 UTC, closed without merging