Clarify the cache behavior in the Ref Guide
apache/solr pull request #2472
Opened 2024-05-21 21:53 UTC by AndreyBozhko

# Description

Clarify that only the filter cache, and not any other caches, can be disabled by the `cache` local parameter.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2024-05-21 22:19 UTC, AndreyBozhko commented on solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
> -Caches can also be disabled on a query-by-query basis with the `cache` parameter, as described in the section xref:query-guide:common-query-parameters.adoc#cache-local-parameter[cache Local Parameter
This sentence is misleading, as only the filter cache inserts/lookups are affected by cache=false query parameter

2024-05-22 11:54 UTC, epugh requested changes
Thanks for the attention to detail.  One question on the query by query nature of filtercache..     Does make you wonder if more caches should be disabled?

2024-05-22 14:39 UTC, AndreyBozhko commented on solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
> -Caches can also be disabled on a query-by-query basis with the `cache` parameter, as described in the section xref:query-guide:common-query-parameters.adoc#cache-local-parameter[cache Local Parameter
@epugh The doc does say that caches can be toggled in solrconfig.xml:
```
All caches can be disabled using the parameter `enabled` with a value of `false`.
```

But the **`cache` local parameter** only works with the filter cache, - so I removed all mentions of that parameter from the doc, and only kept one mention in the `Filter Cache` section (which redirects to Common Query Parameters).

2024-05-22 20:57 UTC, epugh commented
Okay, I added just a tweak after building the ref guide site and reading through it!  thank you!

2024-05-22 20:57 UTC, merged