SOLR-17367 - org.apache.solr.cli.PostTool is ignoring -params option
apache/solr pull request #2557
Opened 2024-07-16 08:44 UTC by bogdanstoik

https://issues.apache.org/jira/browse/SOLR-17367  

# Description

Adding support for -params option in org.apache.solr.cli.PostTool

# Solution

I modified the postData method so that it checks and appends -params value to the solr request

# Tests

I implemented testRunCsvWithCustomSeparatorParam in org.apache.solr.cli.PostToolTest. The test creates a tsv and submits it to the test core. It then checks to see if the index contains exactly 1 document.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2024-07-16 14:53 UTC, epugh commented
thanks for the addition of the tests..  I will inline some comments....   one thing, did you run `gradlew tidy`?  that does some code formatting.

2024-07-16 15:00 UTC, epugh requested changes
Looks like some great progress.  A couple of questions!   When I add it to `CHANGES.txt`, how would you like to be credited?

2024-07-16 18:54 UTC, bogdanstoik commented on solr/core/src/java/org/apache/solr/cli/PostTool.java
> +    params = cli.hasOption("params") ? cli.getOptionValue("params") : "";
That looks way better

2024-07-16 18:56 UTC, bogdanstoik commented on solr/core/src/test/org/apache/solr/cli/PostToolTest.java
> +    String[] args = {
I haven't run gradle tidy after writing the testcase 🤦‍♂️

2024-07-16 18:58 UTC, bogdanstoik commented on solr/core/src/test/org/apache/solr/cli/PostToolTest.java
> +    // Provide the port for the PostTool to look up.
To be honest, i just copied the testRunWithCollectionParam function and modified it. Have little to no experience in java, so i thougt it was safest.

2024-07-16 18:59 UTC, bogdanstoik commented on solr/core/src/test/org/apache/solr/cli/PostToolTest.java
> +    for (int idx = 0; idx < 100; ++idx) {
same as above comment, i just copy-pasted and modified the testRunWithCollectionParam function

2024-07-16 19:09 UTC, bogdanstoik commented
> thanks for the addition of the tests.. I will inline some comments.... one thing, did you run `gradlew tidy`? that does some code formatting.

I did not 🤦‍♂️.
I had a blast writing java for the first time in 10 years. I promise I'll try to contribute more to the project, as it's a key part in my job.

2024-07-16 19:14 UTC, bogdanstoik commented
> Looks like some great progress. A couple of questions! When I add it to `CHANGES.txt`, how would you like to be credited?

Bostoi

Thank you

2024-07-16 19:24 UTC, bogdanstoik commented on solr/core/src/test/org/apache/solr/cli/PostToolTest.java
> +    for (int idx = 0; idx < 100; ++idx) {
looking through the code, i think this loop just tries to make sure the changes are commited to index. it "wants" to find the correct results, after all 😄

2024-07-16 19:25 UTC, bogdanstoik commented on solr/core/src/test/org/apache/solr/cli/PostToolTest.java
> +    String[] args = {
i've ran it just now and it does wrap

2024-07-16 19:27 UTC, bogdanstoik commented
> > thanks for the addition of the tests.. I will inline some comments.... one thing, did you run `gradlew tidy`? that does some code formatting.
> 
> I did not 🤦‍♂️. I had a blast writing java for the first time in 10 years. I promise I'll try to contribute more to the project, as it's a key part in my job.

The only thing i'm not sure about is passing the params to the /extract component of the webMode.

2024-07-17 06:17 UTC, epugh commented
One more thought which is that sometimes I find it easier to write a bats test instead of Java...   post.bats is used to test out the cli against a live solr...

2024-07-17 07:50 UTC, epugh commented
by the way @bogdanstoik how did you find this bug?   Did you have a scripte using the `-params`?

2024-07-17 08:02 UTC, bogdanstoik commented
> by the way @bogdanstoik how did you find this bug? Did you have a scripte using the `-params`?

Yes. I was trying to load a tab-separated csv and it kept complaining about not finding the right columns. I ended up using curl to post my file directly to the update handler, then came back to check if's something in the tool.

2024-07-19 10:25 UTC, epugh approved these changes

2024-07-19 10:25 UTC, merged