SOLR-17479: Deprecate the single letter options
apache/solr pull request #2748
Opened 2024-10-07 15:00 UTC by epugh

https://issues.apache.org/jira/browse/SOLR-17479

# Description

Deprecate single letter options

# Solution

Interesting that in almost none of our tests use the short cut version!

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended, not available for branches on forks living under an organisation)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2024-10-07 15:00 UTC, epugh commented
@malliaridis  and done!

2024-10-07 16:21 UTC, malliaridis requested changes
Additional single-letter uses:
- [ ] solr/packaging/test/test_assert.bats#41 - `-e` should be `--exists`
- [ ] solr/packaging/test/test_assert.bats#54 - `-e` should be `--exists`
- [ ] solr/sorl-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc - The section of `bin/solr assert` mentions all single-letter flags

Could you also mention that the single-letter option deprecation is about `AssertTool` only in the detail and description to avoid any misinterpretations?

2024-10-07 16:21 UTC, malliaridis commented on solr/packaging/test/test_placement_plugin.bats
> +  solr assert --cloud http://localhost:${SOLR_PORT} -t 3000
```suggestion
  solr assert --cloud http://localhost:${SOLR_PORT} --timetout 3000
```

2024-10-07 16:21 UTC, malliaridis commented on solr/packaging/test/test_placement_plugin.bats
> +  solr assert --cloud http://localhost:${SOLR_PORT} -t 3000
```suggestion
  solr assert --cloud http://localhost:${SOLR_PORT} --timeout 3000
```

2024-10-07 17:39 UTC, epugh commented
>     * [ ]  solr/sorl-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc - The section of `bin/solr assert` mentions all single-letter flags

Someday I want to do `bin/solr assert --help` and pipe that output into the Ref Guide!

2024-10-07 20:57 UTC, malliaridis approved these changes
Nice catch of my typo. 👍

2024-10-07 20:57 UTC, malliaridis commented on solr/packaging/test/test_assert.bats
Good catch. That's why I prefer the extended flags in code as well. I thought `-e` was for "exists" because I was expecting "exitcode" to accept an argument. 😅

2024-10-07 23:12 UTC, janhoy approved these changes

2024-10-09 13:20 UTC, malliaridis approved these changes

2024-10-09 16:48 UTC, merged