SOLR-17575: Fixed broken backwards compatibility with the legacy "langid.whitelist" config in Solr Langid
apache/solr pull request #2886
Opened 2024-11-27 04:50 UTC by azagniotov

https://issues.apache.org/jira/browse/SOLR-17575

# Description

Making sure that backwards compatibility with the legacy `"langid.whitelist"` config in Solr Langid works as expected. In other words, the language detection runtime behavior should be the same when the ISO 639-1 language codes specified in the legacy `"langid.whitelist"` OR the current (default) `"langid.allowlist"`.

# Solution

Making sure that if the legacy `"langid.whitelist"` is configured, its value is used as the default value when reading the `LANG_ALLOWLIST` parameter.

# Tests

- Added a sanity unit test to demonstrate that the behavior using the current (default) `"langid.allowlist"` is as expected.
- Added a unit test to demonstrate that the backwards compatibility with the legacy `"langid.whitelist"` works as expected.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended, not available for branches on forks living under an organisation)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] (**N/A**) I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2024-11-27 09:21 UTC, janhoy requested changes
Thanks for the quick turnaround. I enabled PR test runs and see that a the new tests fail

```
   >     org.junit.ComparisonFailure: expected:<[no]> but was:<[sv]>
```

See my comments on how to greatly simplify the tests :)

2024-11-27 09:21 UTC, janhoy commented on solr/modules/langid/src/java/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessor.java
> +          langAllowlist.add(lang.trim());
An alternative is functional style, but up to you:
```java
params.get(LANG_ALLOWLIST, legacyAllowList)
      .flatMap(line -> Arrays.stream(line.split(",")))
      .map(String::trim)
      .filter(lang -> !lang.isEmpty())
      .forEach(langAllowlist::add);
```

2024-11-27 09:21 UTC, janhoy commented on solr/modules/langid/src/test/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessorFactoryTestCase.java
> +    // Make sure that empty language codes have been filtered out and others trimmed.
Should be no need to do an actual detection here (which currently fails tests). Suffice to check that the allowList got populated:
```suggestion
    assertEquals(Set.of("no", "en", "sv"), liProcessor.langAllowlist);
```

2024-11-27 09:21 UTC, janhoy commented on solr/modules/langid/src/test/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessorFactoryTestCase.java
> +    // Make sure that empty language codes have been filtered out and others trimmed.
Same is true here, just test that the allowList got populated:
```suggestion
    assertEquals(Set.of("no", "en", "sv"), liProcessor.langAllowlist);
```

2024-11-27 14:05 UTC, epugh commented
glad to see we are tackling fixing a bug.   In 10x we should move forward and delete the langid.whitelist.....

2024-11-27 14:13 UTC, janhoy commented
> glad to see we are tackling fixing a bug. In 10x we should move forward and delete the langid.whitelist.....

For sure. I expect there to be lots of such cleanup commits on the main branch in the coming weeks.

2024-11-27 22:17 UTC, janhoy approved these changes

2024-11-28 06:56 UTC, janhoy commented
Good. Only one thing missing now. Add a CHANGES.txt line under 9.8.0 Bugfix section, with your own and my name. I’ll then merge and backport.

2024-11-28 07:11 UTC, azagniotov commented
> [janhoy](/janhoy)

@janhoy done!

2024-11-28 09:01 UTC, merged