Update log4j to 2.17 to address CVE-2021-45105
apache/solr pull request #461
Opened 2021-12-20 06:50 UTC by weidongkl

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

Signed-off-by: weidong <weidong@uniontech.com>

https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

2021-12-20 08:59 UTC, janhoy requested changes

2021-12-20 08:59 UTC, janhoy commented on solr/CHANGES.txt
> +* SOLR-15843: Update Log4J to 2.17 (Mike Drob, janhoy, weidongkl)
8.11.1 is released, so you need to file a new JIRA and place a changes entry in the 8.11.2 and 9.0 sections.

2021-12-22 14:48 UTC, janhoy commented
@weidongkl are you able to do the changes, so this can be merged?

2021-12-23 01:14 UTC, weidongkl commented
> @weidongkl are you able to do the changes, so this can be merged?

I'll do it as soon as possible

2021-12-23 09:52 UTC, janhoy commented
Pushed outside of github

2021-12-23 09:52 UTC, closed without merging