Refactor code to minimize access to SolrCore
apache/solr pull request #599
Opened 2022-02-07 08:01 UTC by noblepaul

2022-02-07 16:00 UTC, madrob requested changes
Please include the JIRA number in the issue description.

The JIRA states "This also should help us provide alternate impls which do not require SolrCore access" - can this PR be expanded to include such an alternate implementation?

There are lots of places where we are not null safe now (we might not have been null safe before either). If we're cleaning this code up, we can consider returning an Optional? Not the only idea, there's probably other ways to make this code better for nulls.

2022-02-09 04:01 UTC, noblepaul commented
> can this PR be expanded to include such an alternate implementation?

@madrob , it's coming up in the parent ticket [SOLR-15963](https://issues.apache.org/jira/browse/SOLR-15963)

2022-02-09 19:57 UTC, dsmiley commented
I'm fine with this without a JIRA; it's a pure refactoring -- very simple without any need for an over-arching purpose.  I don't agree with use of Optional for request.getCoreContainer, which is all that this PR seeks to address.  I like that this PR is laser focused and easy to review; thanks for doing this Noble!

2022-02-09 19:58 UTC, dsmiley commented
+1 to merge, BTW.  no CHANGES.txt needed either (in my mind, that's closer to when a JIRA is needed)

2022-02-10 05:45 UTC, noblepaul commented
>1 to merge, BTW. no CHANGES.txt

Thanks @dsmiley

2022-02-10 05:46 UTC, merged